spring:
  h2.console:
    enabled: true
    path: '/console'
  datasource:
   url: 'jdbc:h2:file:C:/Spring/todo-app/todo-db'
   username: 'sa'
   password: 'sa'
  jpa:
   hibernate:
    ddl-auto: validate
management:
  endpoints:
    web:
      exposure:
        include: '*'
keycloak:
  auth-server-url: 'http://localhost:8180/auth'
  realm: 'TodoApp'
  resource: 'todo-spring-client'
  public-client: true
